Homework7: Yanislav Terentev
YanislavTerentev/pymar2024 pull request #5
Opened 2024-05-30 14:37 UTC by YanislavTerentev

2024-05-31 19:15 UTC, Stml89 commented
Next time, pls create a new branch from the `main` branch

2024-05-31 19:30 UTC, Stml89 requested changes

2024-05-31 19:30 UTC, Stml89 commented on Homework/Homework_7/bulls_and_cows.py
I saw exactly the same solution before, did you write this program yourself?

2024-06-01 11:37 UTC, YanislavTerentev commented on Homework/Homework_7/bulls_and_cows.py
I was partially assisted by my colleagues at work when completing the assignment. I did not see the solutions of other students).

2024-06-01 17:57 UTC, Stml89 approved these changes

2024-06-01 18:59 UTC, merged